import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const arcane = localFont({
  src: "../public/arcane.otf",
  variable: "--font-arcane",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${arcane.variable}`}>
        <div className="flex w-full items-center justify-between bg-slate-100 px-8 py-4">

          <div className="font-arcane text-6xl text-amber-500 rounded-md w-16 h-16 px-6">Lejaa</div>

          <nav className="flex space-x-8">
            <Link className="text-black" href="/about">About</Link>
            <Link className="text-black" href="/prices">Prices</Link>
            <Link className="text-black" href="/program">Program</Link>
            <Link className="text-black" href="/dashboard">Dashboard</Link>
          </nav>
          <div className="bg-amber-500 rounded-lg w-32 h-12 flex justify-center items-center">Contact Us</div>
        </div>
        {children}
      </body>
    </html>
  );
}
